### ISSUE TITLE
Add proxy to the scraper

### ISSUE THREAD

**Issue by axelabbas** [supmanyu/InstaScraper#3]
Hey, _After using the scraper for quite a while I started to not get any email, after checking I found that even the accounts that does show their email aren't showing in the scraper, so I tried using vpn and well, it worked out perfectly fine, so it was probably a block/ban for my ip temporary_, **anyways, my request is to add proxy to the scraper, it'll be really helpful and faster than using VPN everytime we want to scrape**

**Comment by axelabbas** [comment]
(just wanted to say that I tried to add proxies myself, and well it's obvious that I couldn't done it because of my low experience in python)

**Comment by supmanyu** [comment]
Unfortunately I haven't been able to focus on updating the scraper too much, because of my work and some personal commitments. i was aware of the IP blocking issue with the scraper. I'll try to push some updates soon. until then I suggest that you can continue using a VPN, and keep a track of this repo for further updates. If you are able to add a proxy somehow, consider making a PR and pushing the changes so that i can merge them and keep the scraper up-to-date.

**Comment by axelabbas** [comment]
That's totally fine, take your time doing it, no pressure, just wanted to say thank you making such a scraper, pretty unique and helpful, haven't seen any free one except this even though I've searched a lot, take your time and thank you so much, I'll try my best to try to get the proxy worrking, also, if you want I can send you what I've done so far to the proxy as if I assume it'll probably make it easier for you to work on it. I'm not so sure about it since as I said, im not very good at python nor programming in general.

Edit: about what I've done so far. I defined a proxy grabber that grabs HTTP proxies from www.sslproxies.org , but with my low experience with python im not sure how to use the proxy while scrapping, The best I managed to do is make the script visit the site where you grab the emails from with proxy but im not sure how to get both to work, the proxy and the scraper. I can send you the code if that'd help.

**Comment by supmanyu** [comment]
I was google-ing around and came across a very simple fix to implement proxies for the website request. On line 39:

```proxies = {"https": "PROXY_URL_HERE"} ```

add a proxy url from ProxyBroker: https://github.com/constverum/ProxyBroker (This is optional, You can use whatever tool you want to find proxies, just make sure the proxies are active so that you dont get a connection error, the proxies from the link you provided do not seem to be working.)

Please pull the latest commits to see the changes.

**Comment by axelabbas** [comment]
Sorry for the late reply I didn't check github till now, Also, what I had in mind is more like a full proxy system kinda thing? as it like it asks for a proxy file (or you could make the script grab proxies from the internet) and it'd use those proxies in the scrapping, not a single proxy url because it'd be more efficient and easier than editing the code everytime you wanna change the proxy? that's just a suggestion that I think it'd make the scraper better, I have a bunch of more ideas in mind too but well, maybe when you are free and you have the time to actually work on the scraper

**Comment by supmanyu** [comment]
I completely agree, what i provided was a quick fix so that you can still use the scraper, configuring a proxy system will require some development, for which i dont have time for right now, unfortunately, if you get around to figuring it out, feel free to make changes to the code and commit to this repo on another branch so that I can monitor your code as well.

**Comment by axelabbas** [comment]
**Old Comment** _Hey, sorry if I'm wasting your time, I have one more request, could you add a time out maybe like 5 secs so it switches the proxy if the connection took more than 5 seconds (thats so you avoid bad/slow proxies) || I'd do it myself but im not sure how to do it_
_anyway to make the bot faster is obviously going to be awesome, thanks for your time_

**New comment**: Nvm! I've finally managed to get the proxy from a specific file to work properly! (I hope), It switches the proxy if it doesn't work for 10 secs, made it so that it grabs the proxies from the file, read it, then check it, if it works it'll use it to scrape! 

The way it'll work: python2 Scraper.py -X proxyfile.txt


I've tested it and it didn't print any error, how ever the scrip is kinda of messy right so I'll try to clean it before publishing it to pull, I hope it doesn't run into any issues, (the proxies only work as Https proxies ofc)
