### ISSUE TITLE
Make the script faster

### ISSUE THREAD

**Issue by axelabbas** [supmanyu/InstaScraper#6]
I'm wondering if using threads would make the script scrape faster, I'm not sure about what does threads exactly get faster so that's my question, if I added threads into the scraper will it scrape faster (I dunno cuz I've never used threads before), If not is there anyway I can make it scrape faster? and if threads do make it faster I'll definitely code it and do a pull request!

**Comment by supmanyu** [comment]
Threads would definitely help with performance, since the throughput will be increased multi-fold, You can go ahead and create another PR to implement multithreading. Good luck!

**Comment by axelabbas** [comment]
Alright, thanks!

**Comment by Axelu2020** [comment]
Hey, I kinda of need your help in implementing threads, when I added this code to the end of the script:

_threadlist = []

for i in range(3):
    thread = threading.Thread(target=init_scraper)
    thread.start()
    threadlist.append(t)

for b in threadlist:
    b.join_

Instead of getting it faster, it instead repeats the same result multiple-times for example:

my input is: user1, user2 etc..

the output: found for user1
found for user1
found for user1
found for user2
found for user2
found for user2

I would appreciate your help, after researching I couldn't figure it out so I thought you're my last hope lol
